name: Firebase Deploy on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  firebase-deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase Authentication
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting